In [131]:
import pandas as pd
import numpy as np
from sklearn  import datasets, linear_model

In [132]:
df=datasets.load_diabetes()

In [133]:
df

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [134]:
dataset= pd.DataFrame(df.data)
dataset

0         1         2         3         4         5         6  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

            7         8         9  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [135]:
dataset.columns=df.feature_names
dataset


age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [136]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


In [137]:
dataset.min()

age   -0.107226
sex   -0.044642
bmi   -0.090275
bp    -0.112399
s1    -0.126781
s2    -0.115613
s3    -0.102307
s4    -0.076395
s5    -0.126097
s6    -0.137767
dtype: float64

In [138]:
dataset.max()

age    0.110727
sex    0.050680
bmi    0.170555
bp     0.132044
s1     0.153914
s2     0.198788
s3     0.181179
s4     0.185234
s5     0.133597
s6     0.135612
dtype: float64

In [139]:
dataset.mean()

age   -1.444295e-18
sex    2.543215e-18
bmi   -2.255925e-16
bp    -4.854086e-17
s1    -1.428596e-17
s2     3.898811e-17
s3    -6.028360e-18
s4    -1.788100e-17
s5     9.243486e-17
s6     1.351770e-17
dtype: float64

In [140]:
dataset.median()

age    0.005383
sex   -0.044642
bmi   -0.007284
bp    -0.005670
s1    -0.004321
s2    -0.003819
s3    -0.006584
s4    -0.002592
s5    -0.001947
s6    -0.001078
dtype: float64

In [141]:
dataset.std()

age    0.047619
sex    0.047619
bmi    0.047619
bp     0.047619
s1     0.047619
s2     0.047619
s3     0.047619
s4     0.047619
s5     0.047619
s6     0.047619
dtype: float64

In [142]:
dataset.corr()

age       sex       bmi        bp        s1        s2        s3  \
age  1.000000  0.173737  0.185085  0.335428  0.260061  0.219243 -0.075181   
sex  0.173737  1.000000  0.088161  0.241010  0.035277  0.142637 -0.379090   
bmi  0.185085  0.088161  1.000000  0.395411  0.249777  0.261170 -0.366811   
bp   0.335428  0.241010  0.395411  1.000000  0.242464  0.185548 -0.178762   
s1   0.260061  0.035277  0.249777  0.242464  1.000000  0.896663  0.051519   
s2   0.219243  0.142637  0.261170  0.185548  0.896663  1.000000 -0.196455   
s3  -0.075181 -0.379090 -0.366811 -0.178762  0.051519 -0.196455  1.000000   
s4   0.203841  0.332115  0.413807  0.257650  0.542207  0.659817 -0.738493   
s5   0.270774  0.149916  0.446157  0.393480  0.515503  0.318357 -0.398577   
s6   0.301731  0.208133  0.388680  0.390430  0.325717  0.290600 -0.273697   

           s4        s5        s6  
age  0.203841  0.270774  0.301731  
sex  0.332115  0.149916  0.208133  
bmi  0.413807  0.446157  0.388680  
bp   0.257650  0.393480  0.390430  
s1   0.542207  0.515503  0.325717  
s2   0.659817  0.318357  0.290600  
s3  -0.738493 -0.398577 -0.273697  
s4   1.000000  0.617859  0.417212  
s5   0.617859  1.000000  0.464669  
s6   0.417212  0.464669  1.000000

In [143]:
dataset.describe()

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17  
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01  
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02  
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03  
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02  
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01

In [144]:
dataset.isnull().sum()

age    0
sex    0
bmi    0
bp     0
s1     0
s2     0
s3     0
s4     0
s5     0
s6     0
dtype: int64

In [145]:
dataset.shape

(442, 10)

In [146]:
x=dataset    
y=df.target

In [147]:
from sklearn.model_selection import train_test_split

In [148]:
x_train,x_test,y_train,y_test=train_test_split (x,y,test_size=0.50,random_state=60)


In [149]:
x_train

age       sex       bmi        bp        s1        s2        s3  \
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
335  0.005383 -0.044642 -0.048241 -0.012556  0.001183 -0.006637  0.063367   
397  0.052606 -0.044642 -0.004050 -0.030907 -0.046975 -0.058307 -0.013948   
415 -0.005515 -0.044642  0.008883 -0.050427  0.025950  0.047224 -0.043401   
340 -0.016412 -0.044642 -0.013751  0.132044 -0.009825 -0.003819  0.019187   
..        ...       ...       ...       ...       ...       ...       ...   
399  0.059871  0.050680  0.022895  0.049415  0.016318  0.011838 -0.013948   
394  0.034443 -0.044642  0.018584  0.056301  0.012191 -0.054549 -0.069172   
70  -0.001882 -0.044642 -0.069797 -0.012556 -0.000193 -0.009143  0.070730   
65  -0.045472  0.050680 -0.024529  0.059744  0.005311  0.014970 -0.054446   
205 -0.030942 -0.044642  0.046607  0.014987 -0.016704 -0.047034  0.000779   

           s4        s5        s6  
2   -0.002592  0.002861 -0.025930  
335 -0.039493 -0.051404 -0.059067  
397 -0.025840  0.036060  0.023775  
415  0.071210  0.014821  0.003064  
340 -0.039493 -0.035816 -0.030072  
..        ...       ...       ...  
399 -0.002592  0.039542  0.019633  
394  0.071210  0.130079  0.007207  
70  -0.039493 -0.062917  0.040343  
65   0.071210  0.042341  0.015491  
205 -0.002592  0.063453 -0.025930  

[221 rows x 10 columns]

In [150]:
x_test

age       sex       bmi        bp        s1        s2        s3  \
195  0.027178  0.050680  0.025051  0.014987  0.025950  0.048477 -0.039719   
39  -0.001882  0.050680  0.014272 -0.074527  0.002559  0.006202 -0.013948   
164  0.045341 -0.044642 -0.019140  0.021872  0.027326 -0.013527  0.100183   
292  0.009016 -0.044642 -0.022373 -0.032077 -0.049727 -0.068641  0.078093   
433 -0.027310 -0.044642 -0.060097 -0.029770  0.046589  0.019980  0.122273   
..        ...       ...       ...       ...       ...       ...       ...   
315  0.009016 -0.044642 -0.020218 -0.053870  0.031454  0.020607  0.056003   
265 -0.034575  0.050680 -0.025607 -0.017135  0.001183 -0.002880  0.008142   
243  0.016281  0.050680 -0.046085  0.011544 -0.033216 -0.016032 -0.010266   
156 -0.016412 -0.044642 -0.010517  0.001215 -0.037344 -0.035760  0.011824   
346  0.005383  0.050680  0.017506  0.032201  0.127771  0.127390 -0.021311   

           s4        s5        s6  
195  0.034309  0.007838  0.023775  
39  -0.002592  0.019196  0.003064  
164 -0.039493  0.017765 -0.013504  
292 -0.070859 -0.062917 -0.038357  
433 -0.039493 -0.051404 -0.009362  
..        ...       ...       ...  
315 -0.039493 -0.010903 -0.001078  
265 -0.015508  0.014821  0.040343  
243 -0.002592 -0.043984 -0.042499  
156 -0.039493 -0.021395 -0.034215  
346  0.071210  0.062578  0.015491  

[221 rows x 10 columns]

In [151]:
y_test

array([122.,  90., 214.,  84.,  72., 280., 171., 128., 332., 142., 214.,
        58.,  64., 186.,  55.,  60., 109., 321.,  84.,  72., 233.,  85.,
       236.,  69., 245., 336., 232., 200., 168.,  51., 164., 118., 191.,
        67., 116., 168.,  93.,  83., 182., 100., 283.,  53., 118.,  48.,
        91., 275.,  99., 179.,  78.,  72., 125., 209., 233., 143., 202.,
       151., 311.,  94., 275., 242., 128., 268., 104.,  69.,  68., 270.,
        94., 111., 245., 161., 113., 167., 308.,  51., 103., 121., 101.,
       120., 196., 109., 148., 178., 154.,  52., 212.,  59.,  87., 270.,
       170., 185.,  80., 198., 129.,  63., 140., 261.,  75., 127.,  55.,
       200.,  39.,  91.,  81., 200., 225.,  55.,  87., 141., 244.,  68.,
       295., 143.,  59., 192., 160.,  81., 210., 175., 281.,  39.,  43.,
       131., 140., 197.,  40., 310., 288., 158., 246.,  84.,  60., 113.,
       189.,  53., 195.,  95., 151.,  90., 129.,  75., 185., 200.,  44.,
        59., 124.,  98., 121., 233.,  52.,  64., 19

In [152]:
y_train

array([141.,  96., 198., 174., 216.,  50., 178.,  42., 101., 208., 107.,
       142., 272.,  97.,  61., 190.,  77., 258., 187.,  54.,  51., 178.,
       126., 147.,  71.,  37., 276., 107.,  91., 235., 219., 139., 150.,
       150., 262., 196., 279., 229., 220.,  72., 258.,  65.,  53.,  49.,
       275.,  85.,  85.,  77., 177.,  71., 158., 253., 292., 109., 200.,
       277., 197., 134., 303., 155., 252.,  77., 110., 132.,  49., 262.,
       272.,  47., 191.,  72.,  70., 283., 144., 101., 115., 134., 128.,
       302., 258.,  63., 281., 174., 180.,  66., 181.,  96., 108.,  96.,
        72.,  71., 131.,  90., 152.,  61.,  68.,  85., 237.,  89., 144.,
       182., 252., 122., 230., 123.,  57., 277., 265.,  42., 230., 145.,
       156., 248.,  90., 242., 113., 142., 317.,  65.,  52.,  79.,  96.,
        74., 206.,  94., 275., 310., 242., 265., 144., 217., 252., 182.,
        95., 137., 153., 144.,  45., 173., 297., 293.,  88., 136., 264.,
       198., 104., 259., 199.,  71., 184.,  70.,  7

In [153]:
# train and test split 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


In [154]:
X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(x_test)

In [155]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score


In [156]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [157]:
mse=cross_val_score(regression,X_train,y_train,scoring='neg_mean_squared_error',cv=20)
mse

array([-1368.05125726, -1822.8420706 , -3828.03596959, -2814.20235447,
       -6993.44956653, -3720.92087893, -5149.52629959, -1634.44009281,
       -2745.83204887, -5416.13943655, -2846.67507005, -2402.03559413,
       -2612.78596924, -3080.28998737, -2339.07834886, -2559.36410198,
       -4000.46615712, -1495.30604416, -3302.67513457, -2838.0041824 ])

In [158]:
import numpy as np
np.mean(mse)

-3148.506028254665

In [159]:
reg_pred=regression.predict(x_test)
reg_pred

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([159.4877822 , 158.32154498, 157.49130261, 154.62689229,
       153.48380474, 161.71849397, 159.57644503, 162.12122383,
       161.69590442, 157.28335109, 157.16550114, 159.60851151,
       156.6855871 , 161.21950352, 157.99391609, 157.76839852,
       156.06318465, 162.09156196, 157.74003902, 155.01112958,
       160.24253132, 158.97178066, 161.67522803, 154.50878629,
       159.10864269, 163.17124956, 162.26503319, 158.41023249,
       158.04451897, 155.02687063, 160.18863018, 158.52531994,
       156.54076412, 157.52663732, 158.46525193, 156.96169378,
       158.20755427, 156.90608862, 156.06517321, 159.3062015 ,
       160.34056108, 157.02342025, 155.07558873, 159.96289776,
       159.37358775, 161.56865878, 153.61453444, 156.13427171,
       156.92181812, 153.94097919, 155.01932157, 159.32283947,
       163.43571023, 158.96207641, 161.46780368, 159.22480441,
       159.59554194, 159.36025524, 162.04241596, 159.3889524 ,
       153.99555419, 161.44054735, 156.71197592, 156.12

In [160]:
from sklearn.metrics import r2_score
score=r2_score(reg_pred,y_test)
score

-797.9138483763147